name: Publish Package

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name:  update package version
        run: npm ci

      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}


      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Deploy Storybook to GitHub Pages
        run: |
          rm -rf storybook-static
          npx build-storybook -o ./storybook-static
          git config --global user.email "valodyapapikyan@gmail.com"
          git config --global user.name "valodyapapikyan"
          git add .
          git commit -m "Deploy Storybook to GitHub Pages"
          git subtree push --prefix storybook-static origin gh-pages
