name: Publish Package

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Specify Node Version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set Git user name
        run: git config user.name "LilitArz"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Create .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_AUTH_TOKEN }}" > ~/.npmrc

      - name: Build
        run: npm run build

      - name: Publish to npm
        run: npm publish

      - name: Deploy
        run: npm run deploy-storybook
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
