name: Slack Notification on Pull Request Events

on:
  pull_request:
    types:
      - opened

jobs:
  send_slack_notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Slack notification
      - run: echo "PIPE_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID|Pipeline#$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
           payload: |
             {
                "attachments": [
                  {
                    "color": "#70aeff",
                    "blocks": [
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "A new pull request is opened"
                        }
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "Author: ${{github.event.pull_request.user.login}}"
                        }
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "#${{github.event.pull_request.number}}: ${{ github.event.pull_request.title }}"
                        }
                      },
                      {
                        "type": "section",
                        "text": {
                          "type": "mrkdwn",
                          "text": "Pull Request URL: ${{github.event.pull_request.html_url}}"
                        }
                      },
                    ]
                  }
                ]
             }
        env:
           SLACK_WEBHOOK_URL: ${{ secrets.WEB_SLACK_WEBHOOK_URL }}
           SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
#           PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
#           PULL_REQUEST_TITLE: ${{ github.event.pull_request.title }}
#           PULL_REQUEST_AUTHOR_NAME: ${{ github.event.pull_request.user.login }}
#           PULL_REQUEST_AUTHOR_ICON_URL: ${{ github.event.pull_request.user.avatar_url }}
#           PULL_REQUEST_URL: ${{ github.event.pull_request.html_url }}
#           PULL_REQUEST_BODY: ${{ github.event.pull_request.body }}
#           PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
#           PULL_REQUEST_COMPARE_BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
#           PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
#           PULL_REQUEST_BASE_BRANCH_NAME: ${{ github.event.pull_request.base.ref }}

